tutorialsIndex_pt = {"I. Profissoes", "II. Ancestral System", "III. Masmorras", "IV. Sistemas", "V. Novo Conteudo"}

tutorialsInfo_pt = {
    {
        {name = "01. Coleta", text = "Voce pode coletar materiais em todo o mundo (plantas, flores, arvores, pedras...). Para comecar a coletar materiais, voce deve obter a ferramenta de coleta apropriada, por exemplo, para mineracao voce precisa de uma picareta, para cortar madeira voce precisa de um machado, para herbalismo voce precisa de uma tesoura Voce pode comprar as ferramentas conversando com cada NPC em sua oficina.", img = "imgs/gathering"},
        {name = "02. Mineracao", text = "A Forja do Mineiro esta localizada na Ilha Teleport no segundo andar, aqui voce encontrara o NPC Elyotrope, Elyotrope vende a primeira picareta para iniciar a mineracao. Compre, colete pecas, faca lingotes pequenos e grandes e vende-los para Elyotrope para ganhar dinheiro.", img = "imgs/minners_forge"}, 
        {name = "03. Cortando arvores", text = "A Forja do Lenhador esta localizada na Ilha do Teleporte. No primeiro andar, aqui voce encontrara o NPC Rostock, que vende o primeiro machado para comecar a derrubar arvores ao redor do mundo. Compre, colete madeira, faca algumas tabuas e venda para Rostock.", img = "imgs/woodcutting_craft"}, 
        {name = "04. Herbalist", text = "A forja do herbalista esta localizada na Ilha Teleport no primeiro andar, aqui voce encontrara o NPC Elyria, que vende a primeira tesoura para comecar a colher plantas ao redor do mundo. Compre, colete plantas e cogumelos e depois criar pocoes sao uteis, venda-as no mercado ou use-as para ajuda-lo nas batalhas.", img = "imgs/herbalist_craft"},
 },
    {
        {name = "01. Sistema Ancestral", text = "O Sistema Ancestral e baseado em tarefas, complete tarefas com o npc Armin disponivel na ilha de teletransporte no meio da ponte e ganhe Pontos Ancestrais para gastar na Loja Ancestral, mas tambem Pontos de Rank Ancestral para aumentar seu Rank Ancestral.\nVoce pode verificar seu status no Sistema Ancestral usando o comando !Ancestral, voce vera seu Rank, Pontos e Tarefas que completou. aceitos, status atuais, etc.\nNos botoes do Menu do cliente, voce encontrara a imagem de um bau, que corresponde a Loja Ancestral onde voce pode comprar asas, auras e outras coisas completando tarefas. diretamente atraves dele no modulo de tarefa para ganhar experiencia, pontos de tarefa, pontos de classificacao e voce pode lutar contra o chefe apos completar a tarefa.", img = "imgs/armin_npc"},
    },	
    {
        {name = "01. Dungeon", text = "Introduzimos um Dungeon System, onde voce lutara contra criaturas e apos matar as criaturas necessarias, voce matara o chefe que aparecera em algum lugar da masmorra. Crie seu proprio time e va para derrotar os chefes A masmorra pode ser iniciada nos botoes de menu do botao Dungeon Finder (espada). Cada masmorra tera dificuldades diferentes. Existem 4 masmorras disponiveis: Bones, Master of the Elements, Forbidden e Rootkraken.", img = "imgs/dungeons"},
    },	
    {
        {name = "01. Tier System", text = "O Tier System e baseado em equipamento personalizado, que permite que voce use uma pedra incrustada de estrela para inserir 3 estrelas vazias no equipamento. Uma vez Se voce inseriu 3 estrelas vazias, voce pode inserir uma pedra estrela seguindo a raridade:\n- Comum (verde)\n- Raro (azul)\n- Muito raro (ouro)\n- Epico (roxo)\n- Lendario (vermelho)\nCada nivel tem 1, 2 ou 3 estrelas.\n\nA primeira estrela usara as estatisticas basicas da atualizacao anterior (ou seja, 1 estrela, nenhuma estatistica primaria ou secundaria sera aumentada).\nA segunda estrela aumentara as estatisticas secundarias (resistencia, velocidade, etc.).\nA terceira estrela aumentara as primeiras estatisticas (habilidades: machado, distancia..., armadura...).\nPara comecar Para adicionar um nivel a um equipamento personalizado, voce deve primeiro derrotar o Mestre dos Elementos e obter o embutimento de estrela, utilizando-o em equipamentos permitidos (Netherwave, Skeletal, Varruth, Seetheras ou Felsinger), Capacete, Armadura, Pernas e Botas apenas para isso. No momento em que voce comecar a incrustar uma pedra, tente a sorte para obter a melhor pedra incrustada para aumentar suas estatisticas.\nDepois de adicionar uma pedra, por exemplo 2 Estrelas Azuis (Raras), a uma equipe e saquear, por exemplo, uma Epica ou Lendaria, e voce quiser adiciona-la a sua equipe, voce precisara usar o Extrator de Estrelas da sua equipe para extrair a pedra embutida em sua equipe, seu artigo voltara a ter 3 estrelas vazias e voce podera inserir a nova. Voce recebera a pedra embutida no equipamento apos minera-la, mas perdera o extrator de estrelas.\nVoce pode encontrar o NPC Taerar na Ilha do Teleporte, mas tambem na entrada do Portal do Azure.", img = "imgs/tiers"},
        {name = "02. Badges", text = "Os emblemas sao novos equipamentos que podem ser equipados em um novo slot. Os emblemas podem ser atualizados com amplificadores para atingir o ultimo nivel, cada emblema e diferente.\nDistintivos Eles sao obtidos matando o chefes do mundo, veja a categoria Ilhas em Novo Conteudo.", img = "imgs/badges"}, 
        {name = "03. Deck System", text = "O Deck System e um novo sistema que permite ao jogador equipar um Deck, adicionar cartas ao seu Deck e ativa-lo para ganhar bonus ou alterar elementos de feitico.\nExistem cartas normais e cartas lendarias, como os Decks (bronze, prata e ouro) obtidos de chefes mundiais nas Ilhas em Novo Conteudo.", img = "imgs/deck"},
        {name = "04. Ship System", text = "Comece a navegar pelo continente e explore novas ilhas, novos monstros, lute contra chefes mundiais incriveis e muito mais!\nPara comecar a navegar, fale com Magnus Blackwater nas docas do porto (disponivel em cada cidade), encontre o comerciante Shipwright na saida norte de Thais, que coleta pecas de navios.\nO oceano e perigoso, preste atencao aonde voce vai, alguns piratas estao perto do mercadorias de ladroes.", img = "imgs/boat"}, 
        {name = "05. Luvas e Cinto", text = "Ha um novo equipamento que um jogador pode usar: luvas e cintos. Cada jogador pode usar apenas um cinto e uma luva por vez. Cintos e luvas oferecem mais estatisticas quando jogador. Eles podem ser fabricados na Ilha de Teleporte, no ultimo andar da oficina do Armeiro.", img = "imgs/belt"},	
	},
    {
        {name = "01. Azure Portals", text = "Azure Portals sao portais aleatorios que aparecem no norte de Thais, nordeste de Roshamuul, oeste de Darashia e sudoeste de Svargrond.\nAntes de entrar, feche No portal voce pode encontrar um NPC chamada Estherya que negocia: Moedas de Pesadelo obtidas matando chefes ou completando tarefas em tarefas antigas, ela vende roupas (roupas) e acessorios (addons).\nO interior do Portal do Azure e muito grande, voce deve encontrar o chefe chamado Azure e derrota-lo, voce ganhara Moedas do Azure que poderao ser usadas na Entrada do Portal do Azure ou no Teleporte a Ilha com Taerar e ganhe uma recompensa, novos conjuntos que podem incorporar novas estrelas e alcancar o poder de novos conjuntos.\nSao 4 novos conjuntos, Netherwave (Feiticeiro e Druidas), Varruth e Seetheras (Cavaleiros) e Felsinger (Paladinos). Troque Moedas Azure com o NPC Taerar na entrada dos Portais Azure ou na Ilha de Teleporte perto do NPC Armin.", img = "imgs/estherya"},
        {name = "02. Mapas de Expansao", text = "Ha muito conteudo personalizado, mas tambem conteudo que voce ja conhece e que e otimo encontrar aqui:\nBiblioteca Secreta, Acesso: Isla del Rey (ilha do rei) usando uma foice no altar, Nivel: 250+\nFalcon Bastion, Acesso pela Ilha de Teleporte, Nivel: 200+\nCobra Bastion, Acesso: Ilha de Teleporte, Nivel: 200+\n Grave Danger Bosses, Acesso: Igual ao mapa real, Nivel: 200+\n Bruster Spectres, Lions, Deep Desert, Acesso: De qualquer navio para Kilmaresh (ao norte de Kilmaresh), Nivel: 160 + \n Bounac, Acesso: De qualquer navio, Nivel: 220+\n Soulwar Grounds and Bosses, Acesso: De qualquer navio para Kilmaresh (Central Top Mountain), Nivel: 300+\n Kilmaresh, Urmahlullu's, Acesso: de qualquer navio para Kilmaresh Central Under Kilmaresh, Nivel: 250+\n Rotten Blood, Acesso: de qualquer navio para Kilmaresh (South Kilmaresh, Portal), Nivel: 300+.", img = "imgs/bakragore"},
        {name = "03. As ilhas", text = "Existem 9 novas ilhas espalhadas pelo continente, voce pode acessa-las navegando pelo continente, onde voce pode encontrar novos monstros e Chefes Mundiais em cada ilha. Os Chefes Mundiais Eles aparecem em um determinado horario da semana, preste atencao no horario de respawn, encontre jogadores e derrote-os para coletar cartas, decks, insignias, equipamentos e recursos de upgrade.", img = "imgs/worldbosses"},
        {name = "04. As Expedicoes", text = "As Expedicoes estao localizadas na nova ilha Vyrsk, acessivel a partir do navio de Thais. Ao chegar a Vyrsk, voce pode pegar um navio para diferentes novas ilhas: Hallowfall, Dorn, Vardenfell e Frosthold , incluindo a Ilha Vyrsk, em cada ilha voce pode ganhar reputacao fazendo expedicoes, as expedicoes aparecerao aleatoriamente nas ilhas todos os dias, voce sera informado sobre as expedicoes se estiver por perto das ilhas Apos completar uma expedicao, voce ganhara reputacao e moedas relacionadas a ilha da expedicao, voce pode troca-las no deposito na ilha de Vyrsk (escadas para o andar inferior), com o NPC correspondente na reputacao. espere para ser derrotado, um por ilha, eles aparecem aleatoriamente a cada dia. O ultimo (Emberlord Zanarth) pode ser acessado atraves do deposito de Vyrsk depois. derrote cada chefe da ilha 5 vezes.", img = "imgs/expedition"},
    }
}