tutorialsIndex_es = {"I. Professiones", "II. Ancestral System", "III. Mazmorras", "IV. Sistemas", "V. Nuevo Contenido"}

tutorialsInfo_es = {
    {   
        {name = "01. Recoleccion", text = "Puedes recolectar materiales en todo el mundo (plantas, flores, arboles, piedras...). Para comenzar a recolectar materiales, debes obtener la herramienta adecuada para recolectar, por ejemplo, para la mina necesitas un pico, para cortar madera necesitas un hacha, para herbolario necesitas una tijera. Puedes comprar las herramientas hablando con cada NPC en su taller.", img = "imgs/gathering"},
        {name = "02. Mineria", text = "La Forja del Minero se encuentra en la Teleport Island en el segundo piso, aqui encontraras al NPC Elyotrope, Elyotrope vende el primer pico para comenzar a minar. Compralo, recolecta piezas, fabrica lingotes pequenos y grandes y vendelos a Elyotrope para ganar dinero.", img = "imgs/minners_forge"}, 
        {name = "03. Tala de arboles", text = "La Forja del lenador se encuentra en la Teleport Island En el primer piso, aqui encontraras al PNJ Rostock, que vende la primera hacha para empezar a cortar arboles en todo el mundo. Comprala, recoge madera, fabrica algunas tablas y vendela a Rostock.", img = "imgs/woodcutting_craft"}, 
        {name = "04. Herbolario", text = "La forja del herbolario se encuentra en la Teleport Island en el primer piso, aqui encontraras al PNJ Elyria, que vende las primeras tijeras para empezar a cosechar plantas en todo el mundo. Comprala, recoge plantas y hongos y luego fabrica pociones. Las pociones son utiles, vendelas en el mercado o usalas para ayudarte en las batallas.", img = "imgs/herbalist_craft"},
    },
    {
        {name = "01. Sistema Ancestral", text = "El Sistema Ancestral se basa en tareas, completa tareas con el npc Armin disponible en la teleport island en el medio del puente y gana Puntos Ancestrales para gastar en la Tienda Ancestral, pero tambien Puntos de Rango Ancestral para aumentar tu Rango Ancestral.\nPuedes verificar tu estado en el Sistema Ancestral usando el comando !Ancestral, veras tu Rango, Puntos y Tareas que has aceptado, estados actuales, etc.\nEn los botones del Menu en el cliente, encontraras una imagen de un cofre, que corresponde a la Tienda Ancestral donde puedes comprar wings, auras y otras cosas al completar tareas. Tambien puedes hacer tareas directamente a traves del modulo de tareas para ganar Experiencia, Puntos de Tarea, Puntos de Rango y podras luchar contra el jefe después de completar la tarea.", img = "imgs/armin_npc"},
    },
    {
        {name = "01. Mazmorra", text = "Introdujimos un Sistema de mazmorras, donde lucharas contra criaturas y, despues de matar las criaturas requeridas, mataras al jefe que aparecera en algun lugar de la mazmorra. Crea tu propio equipo y ve a derrotar a los jefes. La mazmorra se puede iniciar en los botones del menu en el boton Buscador de mazmorras (espada). Cada mazmorra tendra diferentes dificultades. Ahora hay 4 mazmorras disponibles: Bones, Master of the Elements, Forbidden y Rootkraken.", img = "imgs/dungeons"},
    },
    {
        {name = "01. Sistema de niveles", text = "El sistema de niveles (Tier System) se basa en equipos personalizados, que te permite usar una piedra de incrustacion de estrellas para insertar 3 estrellas vacias en el equipo. Una vez que hayas insertado 3 estrellas vacias, puedes insertar una piedra de estrella siguiendo la rareza:\n- Comun (verde)\n- Raro (azul)\n- Muy raro (dorado)\n- Epico (morado)\n- Legendario (rojo)\nCada nivel tiene 1, 2 o 3 estrellas.\n\nLa primera estrella tomara las estadisticas base de la mejora anterior (es decir, 1 estrella, no se incrementan las estadisticas primarias o secundarias).\nLa segunda estrella incrementara las estadisticas secundarias (resistencia, velocidad, etc.).\nLa tercera estrella incrementara las primeras estadisticas (habilidades: hacha, distancia..., armadura...).\nPara comenzar a agregar un nivel a un equipo personalizado, primero debes derrotar al Maestro de los elementos y obtener la incrustacion de estrellas, usandola en equipo permitido (Netherwave, Skeletal, Varruth, Seetheras o Felsinger), Casco, Armadura, Piernas y Botas solo a ese momento podras comenzar a incrustar una piedra, prueba tu suerte para obtener la mejor Piedra de Incrustacion para aumentar tus estadisticas.\nDespues de agregar una piedra, por ejemplo 2 Estrellas Azules (Raras), a un equipo y saquearas por ejemplo una Epica o Legendaria, y deseas agregarla a tu equipo, necesitaras usar el Extractor de Estrellas en tu equipo para extraer la piedra incrustada en tu equipo, tu articulo volvera a tener 3 estrellas vacias y podras insertar la nueva. Recibiras la piedra incrustada en el equipo despues de extraerla, pero perderas el extractor de estrellas.\nPuedes encontrar al NPC Taerar en la Teleport Island pero tambien en la entrada dentro del Portal Azure.", img = "imgs/tiers"},
		{name = "02. Insignias", text = "Las insignias (Badges) son equipos nuevos que se pueden equipar en una nueva ranura. Las insignias se pueden mejorar con amplificadores para alcanzar el iltimo nivel, cada insignia es diferente.\nLas insignias se obtienen matando a los jefes del mundo, consulte la categoria Las Islas en Nuevo Contenido.", img = "imgs/badges"}, 
        {name = "03. Sistema Deck", text = "El sistema Deck es un nuevo sistema que permite al jugador equipar un Deck, puede agregar cartas a su Deck y activarlo para obtener bonificaciones o cambiar elementos de hechizos.\nHay cartas normales y cartas legendarias, como los Deck (bronce, plata y oro) que se obtienen de los jefes del mundo en Las Islas en Nuevo Contenido.", img = "imgs/deck"}, 
        {name = "04. Sistema de barcos", text = "¡Comience a navegar por el continente y explore nuevas islas, nuevos monstruos, luche contra increibles jefes del mundo y mucho mas!\nPara comenzar a navegar, hable con Magnus Blackwater en los muelles del puerto (disponible en cada ciudad), encuentra al comerciante Shipwright en la salida norte de Thais, quien recolecta partes de barco.\nEl oceano es peligroso, presta atencion por donde vas, algunos piratas estan cerca de las mercancias de los ladrones.", img = "imgs/boat"}, 
        {name = "05. Guantes y cinturon", text = "Hay un nuevo equipo que un jugador puede usar: guantes y cinturones. Cada jugador puede usar solo un cinturon y un guante al mismo tiempo. Los cinturones y guantes ofrecen mas estadísticas al jugador. Se pueden fabricar en la Teleport Island en el ultimo piso del taller Armorsmith.", img = "imgs/belt"},
    },
    {
		{name = "01. Portales de Azure", text = "Los Portales de Azure son portales aleatorios que aparecen en el norte de Thais, al noreste de Roshamuul, al oeste de Darashia y al suroeste de Svargrond.\nAntes de entrar, cerca del portal puedes encontrar un NPC llamado Estherya que comercia: Monedas de pesadilla (Nightmare Coins) que se obtienen matando jefes o completando tareas en tareas ancestrales, ella vende atuendos (outfits) y complementos (addons).\nEl interior del Portal Azure es muy grande, debes encontrar al jefe llamado Azure y derrotarlo, ganaras Monedas de Azure que se pueden usar en la Entrada del Portal Azure o en la Teleport Island con Taerar y obtener una recompensa, nuevos sets que pueden incrustar nuevas estrellas y alcanzar el poder de los nuevos conjuntos.\nHay 4 conjuntos nuevos, Netherwave (Sorcerer y Druids), Varruth y Seetheras (Knights) y Felsinger (Paladins). Intercambia Monedas de Azure con el NPC de Taerar en la entrada de los Portales de Azure o en la Teleport Island cerca del NPC Armin.", img = "imgs/estherya"},
        {name = "02. Mapas de expansion", text = "Hay mucho contenido personalizado, pero tambien contenido que ya conoces y que es genial encontrar aqui:\nBiblioteca secreta (Secret Library), Acceso: Isla del Rey (isle of king) usando una guadaña(scythe) en el altar, Nivel: 250+\nFalcon Bastion, Acceso desde la Teleport Island, Nivel: 200+\nCobra Bastion, Acceso: Desde la Teleport Island, Nivel: 200+\n Grave Danger Bosses, Acceso: Igual que el mapa real, Nivel: 200+\n Bruster Spectres, Lions, Deep Desert, Acceso: Desde cualquier barco a Kilmaresh (norte de Kilmaresh), Nivel: 160+\n Bounac, Acceso: Desde cualquier barco, Nivel: 220+\n Soulwar Grounds y Bosses, Acceso: Desde cualquier barco a Kilmaresh (Central Top Mountain), Nivel: 300+\n Kilmaresh, Urmahlullu's, Acceso: desde cualquier barco a Kilmaresh Central Under Kilmaresh, Nivel: 250+\n Rotten Blood, Acceso: desde cualquier barco a Kilmaresh (South Kilmaresh, Portal), Nivel: 300+.", img = "imgs/bakragore"},
        {name = "03. Las islas", text = "Hay 9 islas nuevas repartidas un poco por todo el continente, puedes acceder a ellas navegando por el continente, donde puedes encontrar en cada isla, nuevos monstruos y World Bosses. Los World Bosses aparecen a una hora determinada de la semana, presta atencion al tiempo de reaparicion, encuentra jugadores y derrotalos para recolectar cartas, mazos, insignias, equipo y recursos de mejora.", img = "imgs/worldbosses"},
        {name = "04. Las expediciones", text = "Las expediciones se encuentran en la nueva isla Vyrsk, accesible desde el barco de Thais. Al llegar a Vyrsk, puedes tomar un barco a nuevas islas diferentes: Hallowfall, Dorn, Vardenfell y Frosthold, incluida la isla Vyrsk, en cada isla puedes obtener reputacion haciendo expediciones, las expediciones apareceran aleatoriamente en las islas cada dia, se te informara sobre las expediciones si estas cerca de las islas. Despues de completar una expedicion, ganaras reputacion y monedas relacionadas con la isla de la expedicion, puedes intercambiarlas en el depot en la isla Vyrsk (escaleras para el piso de abajo), con el NPC correspondiente sobre la reputacion. Nuevos jefes esperan ser derrotados, uno por isla, aparecen aleatoriamente cada dia. Se puede acceder al ultimo (Emberlord Zanarth) a traves del depot de Vyrsk despues de derrotar 5 veces a cada jefe de las islas.", img = "imgs/expedition"},

	
	},			
}